// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyovnvuluyosjnabrzjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5b3ZudnVsdXlvc2puYWJyempjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMjE0MzIsImV4cCI6MjA3MTc5NzQzMn0.G3HlqGeyLS_39jxbrKtttcsE93A9WvFSEByJow--470";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Test basic connection and clear any problematic data
(async () => {
  try {
    console.log('Testing Supabase connection...');
    console.log('Supabase URL:', SUPABASE_URL);
    console.log('API Key (first 20 chars):', SUPABASE_PUBLISHABLE_KEY.substring(0, 20) + '...');
    
    // Clear any corrupted session data and potential monitoring artifacts
    const clearSession = () => {
      // Clear Supabase auth tokens
      localStorage.removeItem('sb-tyovnvuluyosjnabrzjc-auth-token');
      localStorage.removeItem('supabase.auth.token');
      
      // Clear any potential monitoring or log-related cached data
      const keysToRemove = [];
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && (key.includes('edge-function') || key.includes('logs') || key.includes('monitoring'))) {
          keysToRemove.push(key);
        }
      }
      keysToRemove.forEach(key => localStorage.removeItem(key));
      
      console.log('Cleared potentially corrupted session and monitoring data');
    };
    
    // Test connection with a simple query
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      console.error('Session check failed:', error);
      clearSession();
    } else {
      console.log('Session check successful:', data.session ? 'authenticated' : 'not authenticated');
    }
  } catch (err) {
    console.error('Connection test failed:', err);
    // Clear all localStorage except essential items on connection failure
    const essentialKeys = ['theme', 'language'];
    const allData: Record<string, string> = {};
    essentialKeys.forEach(key => {
      const value = localStorage.getItem(key);
      if (value) allData[key] = value;
    });
    
    localStorage.clear();
    
    // Restore essential items
    Object.entries(allData).forEach(([key, value]) => {
      localStorage.setItem(key, value);
    });
    
    console.log('Cleared localStorage and restored essential data due to connection failure');
  }
})();